import { StyleSheet } from 'react-native';

export const moduleStyles = StyleSheet.create({
  content: { padding: 16, paddingBottom: 80 },
  header: {
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 16,
    marginBottom: 16,
  },
  title: { fontSize: 22, fontWeight: '800', color: '#0f172a' },
  subtitle: { marginTop: 4, color: '#64748b', fontSize: 13 },
  contextRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 10 },
  contextChip: {
    backgroundColor: '#eef2ff',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginRight: 6,
    marginTop: 4,
  },
  contextChipText: { color: '#3730a3', fontSize: 12, fontWeight: '700' },
  card: {
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
    marginBottom: 10,
  },
  cardRow: { flexDirection: 'row', alignItems: 'center' },
  cardTitle: { fontSize: 15, fontWeight: '700', color: '#0f172a' },
  cardMeta: { color: '#64748b', fontSize: 12, marginTop: 2 },
  badge: {
    backgroundColor: '#dcfce7',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginLeft: 8,
  },
  badgeText: { color: '#166534', fontSize: 11, fontWeight: '800' },
  badgeMuted: { backgroundColor: '#f1f5f9' },
  badgeMutedText: { color: '#475569' },
  empty: {
    backgroundColor: '#f8fafc',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderStyle: 'dashed',
    padding: 20,
    alignItems: 'center',
  },
  emptyText: { color: '#64748b', fontSize: 13, textAlign: 'center' },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
    marginTop: 6,
  },
  primaryBtn: {
    backgroundColor: '#2563eb',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: 'center',
    marginTop: 4,
  },
  primaryBtnText: { color: '#fff', fontWeight: '700' },
  secondaryBtn: {
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: 'center',
    marginTop: 4,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#fff',
  },
  secondaryBtnText: { color: '#0f172a', fontWeight: '700' },
});

export default moduleStyles;
